site_name: 清小搭技术团队
theme:
  name: material
nav:
  - 首页: index.md
  - 功能介绍:
      - 知识问答: arch/rag.md
      - 智能摘录: arch/webnote.md
      - 工具调用: arch/mcp_tools.md
      - 数学智能体: arch/math.md
  - FAQ: faq.md
docs_dir: docs
site_dir: site
use_directory_urls: false