site_name: 清小搭技术团队
theme:
  name: material
nav:
  - 首页: index.md
  # - 整体架构:
  #     - 系统总览: arch/overview.md
  #     - RAG 架构: arch/rag.md
  #     - 多模态输入: arch/multimodal.md
  #     - 推理引擎优化: arch/inference.md
  - FAQ: faq.md
