site_name: 清小搭技术团队
theme:
  name: material
  features:
    - navigation.expand
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.admonitions  # 支持提示框样式
    - content.code.copy
extra_css:
  - stylesheets/extra.css  # 引入自定义样式

plugins:
  - search
  - macros
  
nav:
  - 首页: index.md
  - 技术介绍:
      - 检索模型: arch/embedding.md
      - 智能摘录: arch/webnote.md
      - 评测框架: arch/rag_eval.md
      - 知识问答: arch/rag.md
  - 学术论文: papers.md
  - 开源项目: projects.md
docs_dir: docs
site_dir: site
use_directory_urls: false